# Generated by Django 6.0.4 on 2026-09-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
            ],
            options={
                'unique_together': {('nome', 'fabricante')},
            },
        ),
    ]
